### ISSUE TITLE
How to train a model from scratch？

### ISSUE THREAD

**Issue by radish512** [mxin262/Bridging-Text-Spotting#3]
Dear author, I noticed that only the pretraining code is provided in the document, like
 `python tools/train_net.py --config-file configs/Bridge/TotalText/R_50_poly.yaml --num-gpus 4  MODEL.WEIGHTS totaltext_final.pth`

Is there any code available for training from scratch?

**Comment by mxin262** [comment]
This command is for training from scratch. The MODEL.WEIGHTS totaltext_final.pth represents the weight of DPText-DETR or TESTR. The pretrained DiG is presented [here](https://github.com/mxin262/Bridging-Text-Spotting/blob/29f78a24fba2afebf0ae33525e87160b3afc98bd/adet/modeling/DPtext_detr.py#L153)

**Comment by radish512** [comment]
Do you mean that by removing `MODEL.WEIGHTS totaltext_final.pth`, it becomes the code for training the model from scratch?

**Comment by radish512** [comment]
Do you mean that by removing `MODEL.WEIGHTS totaltext_final.pth`, it becomes the code for training the model from scratch?

**Comment by mxin262** [comment]
Our method is based on the pretrained detector and recognizer. Therefore, you need to load pre-trained detectors and recognizers. If you want to train the detector and recognizer from scratch, you can remove the file MODEL.WEIGHTS totaltext_final.pth, and it will become an end-to-end text spotting system.
