### ISSUE TITLE
Can't see results of text ocr

### ISSUE THREAD

**Issue by JY-CCK** [mxin262/Bridging-Text-Spotting#4]
Hello. 
First of all, thanks for sharing nice works :>

I want to get a result of detection + recognition (text spotting).
But, it only show detection results without any text label.

I followed the rule that you mentioned like below
`python demo/demo.py --config-file configs/Bridge/ICDAR15/R_50_poly.yaml --input input.png --output output.jpg --opts MODEL.WEIGHTS ./pretrained_models/Bridge_ic15.pth`

![output](https://github.com/mxin262/Bridging-Text-Spotting/assets/152348775/bdf47055-c002-4cd0-9c7d-648eabc0bec7)

Any reasons?

Thanks.

**Comment by mxin262** [comment]
I have updated the visualizer.
