### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by yyyyyxie** [mxin262/Bridging-Text-Spotting#5]
![4181713782253_ pic](https://github.com/mxin262/Bridging-Text-Spotting/assets/101948858/d36b494e-4dcf-402f-9a3a-e8b31b8b71ad)

I downloaded the annotation files for the tt dataset using the link you provided and successfully loaded the dataset and weights. However, I encountered this error during the forward process. I am not sure whether the issue is due to the code, my configuration, or a problem with a third-party library. I hope the author can provide some clarification. Thank you.

**Comment by mxin262** [comment]
You need to use the detectron2 in this repositories.
