### ISSUE TITLE
What's the difference between the raw dataset and the rotated dataset?

### ISSUE THREAD

**Issue by pd162** [mxin262/Bridging-Text-Spotting#6]
Thanks for your outstanding work! I have noticed that the previous works use rotated datasets, like Total-Text. I want to know the difference between them and why the rotated images perform better than raw images.

**Comment by mxin262** [comment]
The difference between them is that the rotated datasets are enhanced by rotation. The rotated images may improve the performance with the data enhancement.

**Comment by pd162** [comment]
> The difference between them is that the rotated datasets are enhanced by rotation. The rotated images may improve the performance with the data enhancement.

Thanks for your reply. I have conducted an experiment for inferencing the Total-Text rather than Total-Text (rotated) and keeping the same test annotation. It decreased 1.0% on detection-only evaluation and 0.7% on e2e evaluation. So I don't think the training stage brings the difference. 

And I wonder the earliest paper who uses datasets of the rotated version.  Maybe that paper could answer this question.

**Comment by mxin262** [comment]
The rotated datasets are from DPText-DETR.

**Comment by pd162** [comment]
> The rotated datasets are from DPText-DETR.

Thanks！
